// Generated by the protocol buffer compiler.  DO NOT EDIT!

#ifndef PROTOBUF_commitlog_2eproto__INCLUDED
#define PROTOBUF_commitlog_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "waveclient-rpc.pb.h"

namespace commitlog {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_commitlog_2eproto();
void protobuf_AssignDesc_commitlog_2eproto();
void protobuf_ShutdownFile_commitlog_2eproto();

class ProtocolSubmitRequestList;

// ===================================================================

class ProtocolSubmitRequestList : public ::google::protobuf::Message {
 public:
  ProtocolSubmitRequestList();
  virtual ~ProtocolSubmitRequestList();
  
  ProtocolSubmitRequestList(const ProtocolSubmitRequestList& from);
  
  inline ProtocolSubmitRequestList& operator=(const ProtocolSubmitRequestList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtocolSubmitRequestList& default_instance();
  void Swap(ProtocolSubmitRequestList* other);
  
  // implements Message ----------------------------------------------
  
  ProtocolSubmitRequestList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtocolSubmitRequestList& from);
  void MergeFrom(const ProtocolSubmitRequestList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .waveserver.ProtocolSubmitRequest requests = 1;
  inline int requests_size() const;
  inline void clear_requests();
  static const int kRequestsFieldNumber = 1;
  inline const ::google::protobuf::RepeatedPtrField< ::waveserver::ProtocolSubmitRequest >& requests() const;
  inline ::google::protobuf::RepeatedPtrField< ::waveserver::ProtocolSubmitRequest >* mutable_requests();
  inline const ::waveserver::ProtocolSubmitRequest& requests(int index) const;
  inline ::waveserver::ProtocolSubmitRequest* mutable_requests(int index);
  inline ::waveserver::ProtocolSubmitRequest* add_requests();
  
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::waveserver::ProtocolSubmitRequest > requests_;
  friend void  protobuf_AddDesc_commitlog_2eproto();
  friend void protobuf_AssignDesc_commitlog_2eproto();
  friend void protobuf_ShutdownFile_commitlog_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ProtocolSubmitRequestList* default_instance_;
};
// ===================================================================


// ===================================================================


// ===================================================================

// ProtocolSubmitRequestList

// repeated .waveserver.ProtocolSubmitRequest requests = 1;
inline int ProtocolSubmitRequestList::requests_size() const {
  return requests_.size();
}
inline void ProtocolSubmitRequestList::clear_requests() {
  requests_.Clear();
}
inline const ::google::protobuf::RepeatedPtrField< ::waveserver::ProtocolSubmitRequest >&
ProtocolSubmitRequestList::requests() const {
  return requests_;
}
inline ::google::protobuf::RepeatedPtrField< ::waveserver::ProtocolSubmitRequest >*
ProtocolSubmitRequestList::mutable_requests() {
  return &requests_;
}
inline const ::waveserver::ProtocolSubmitRequest& ProtocolSubmitRequestList::requests(int index) const {
  return requests_.Get(index);
}
inline ::waveserver::ProtocolSubmitRequest* ProtocolSubmitRequestList::mutable_requests(int index) {
  return requests_.Mutable(index);
}
inline ::waveserver::ProtocolSubmitRequest* ProtocolSubmitRequestList::add_requests() {
  return requests_.Add();
}


}  // namespace commitlog

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

#endif  // PROTOBUF_commitlog_2eproto__INCLUDED
